#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright Theodore Robert Campbell Jr <trcjr@stupidfoot.com>

"""
Generate build metadata header for SparkMiner.

Emits include/build_info_auto.h with:
- git hash / describe / dirty state
- PlatformIO env + board + MCU
- build timestamp (UTC)
"""

from datetime import datetime, timezone
from pathlib import Path
import subprocess

Import("env")


def _run(cmd, cwd):
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return ""


def _c_string(value):
    # Minimal escaping for generated C string literals.
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_build_info(_source, _target, _env):
    project_dir = Path(env.subst("$PROJECT_DIR"))
    include_dir = project_dir / "include"
    include_dir.mkdir(parents=True, exist_ok=True)
    out_file = include_dir / "build_info_auto.h"

    pio_env = str(env.get("PIOENV", "unknown"))
    pio_board = str(env.get("BOARD", "unknown"))

    board_cfg = env.BoardConfig()
    pio_mcu = str(board_cfg.get("build.mcu", "unknown"))
    pio_f_cpu = str(board_cfg.get("build.f_cpu", "unknown"))

    git_hash = _run(["git", "rev-parse", "--short", "HEAD"], project_dir)
    git_hash = git_hash if git_hash else "nogit"

    git_describe = _run(["git", "describe", "--tags", "--always", "--dirty"], project_dir)
    git_describe = git_describe if git_describe else "nogit"

    # Dirty state: true if any tracked/untracked changes are present.
    status = _run(["git", "status", "--porcelain"], project_dir)
    git_dirty = "1" if status else "0"

    # Build timestamp in UTC for cross-machine comparability.
    build_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    content = f"""// Auto-generated by scripts/gen_build_info.py. Do not edit.
#ifndef BUILD_INFO_AUTO_H
#define BUILD_INFO_AUTO_H

#define BUILD_GIT_HASH \"{_c_string(git_hash)}\"
#define BUILD_GIT_DESCRIBE \"{_c_string(git_describe)}\"
#define BUILD_GIT_DIRTY {git_dirty}

#define BUILD_PIO_ENV \"{_c_string(pio_env)}\"
#define BUILD_PIO_BOARD \"{_c_string(pio_board)}\"
#define BUILD_PIO_MCU \"{_c_string(pio_mcu)}\"
#define BUILD_PIO_F_CPU \"{_c_string(pio_f_cpu)}\"

#define BUILD_UTC_TIMESTAMP \"{_c_string(build_utc)}\"

#endif // BUILD_INFO_AUTO_H
"""

    out_file.write_text(content, encoding="utf-8")
    print(f"[BUILD-INFO] Generated: {out_file}")


# Run before compile so header is always available.
generate_build_info(None, None, env)
