// Auto-generated by scripts/gen_build_info.py. Do not edit.
#ifndef BUILD_INFO_AUTO_H
#define BUILD_INFO_AUTO_H

#define BUILD_GIT_HASH "f2b77c9"
#define BUILD_GIT_DESCRIBE "f2b77c9-dirty"
#define BUILD_GIT_DIRTY 1

#define BUILD_PIO_ENV "heltec-wifi-lora32-v3"
#define BUILD_PIO_BOARD "heltec_wifi_lora_32_V3"
#define BUILD_PIO_MCU "esp32s3"
#define BUILD_PIO_F_CPU "240000000L"

#define BUILD_UTC_TIMESTAMP "2026-05-14T18:06:51Z"

#endif // BUILD_INFO_AUTO_H
